name: RedstoneMobSpawn
version: 1.1
description: Lets you spawn a mob based from redstone using a sign
author: VicWhiten
website: www.github.com/VicWhiten
main: com.bukkit.vicwhiten.redstonemobspawn.RedstoneMobSpawn
